
############################################################################################################################
### This code replicates Figure 2 and Tables 5 to 7 of the paper:														 ###
### 'Combining Value-at-Risk and Expected Shortfall Forecasts via the Model Confidence Set'								 ###
############################################################################################################################

#### Analysis performed using R version 4.4.3

###################################
#### Load the libraries and functions
###################################

library(xts)			# Version used: 0.14.1
library(rugarch)		# Version used: 1.5.3
library(np)     		# Version used: 0.60.18
library(esback)			# Version used: 0.3.1
library(GAS)			# Version used: 0.3.4.1 
						# Currently, the GAS package has been removed from the CRAN. But previous versions
						# are available at https://cran.r-project.org/src/contrib/Archive/GAS/
library(zoo)			# Version used: 1.8.13
library(DT)				# Version used: 0.33
library(htmltools)		# Version used: 0.5.8.1

### To install GAS:

#install.packages("https://cran.r-project.org/src/contrib/Archive/GAS/GAS_0.3.4.1.tar.gz",
#                 repos = NULL,
#                 type = "source")


source('functions/main_functions.R')

##########################################
#### Load data for plots 
##########################################

# The user can load either "data/results/shanghai_comp_final_results_precomputed.RData" or "data/results/shanghai_comp_final_results_generated.RData" 
# generated by "code/3_from_intermediary_files_to_final_files.R"

load("data/results/shanghai_comp_final_results_precomputed.RData")

#############################################################################
#### shanghai_comp_final_results_precomputed includes:
## r_t_oos_full_plot				: daily log-returns for the training plots;
## r_t_oos_full					: daily log-returns for the out-of-sample period;
## nstep							: total number of model re-estimations (i.e., length of the out-of-sample period);
## lab_full						: model labels, including 32 models, 4 benchmarks (EW-Comb, Median-Comb, RS-Comb, MS-Comb),
##           							and 6 proposed combined predictors (MCS-Comb, WL-MCS-Comb, MCS-RS-Comb, WL-MCS-RS-Comb, 
##           							MCS-MS-Comb, WL-MCS-MS-Comb);
## tau							: coverage level;
## Backtesting_pvalues			: p-values of the six backtests (see Table 4 in the paper), by model (32) and over nstep;
## db_loss_oos					: matrix of FZ losses for the out-of-sample period for the 42 models and combined predictors;
## VaR_oos_ev and ES_oos_ev		: matrices of VaR and ES for the out-of-sample period
##                           			for the 42 models and combined predictors;
## MCS_est_included				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                  					from the Model Confidence Set (MCS), using the unweighted FZ loss;
## MCS_est_included_w				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                     				from the Model Confidence Set (MCS), using the weighted FZ loss.
#############################################################################

###################################
#### Replication of Figure 2(a)
###################################

plot_inclusion(
  X = Backtesting_pvalues,
  nstep = nstep,
  lab_full = lab_full,
  r_t_plot = r_t_oos_full_plot,
  N_model = 32,
  square_col="green",
  input_type = "Backtesting"
)

###################################
#### Replication of Figure 2(b)
###################################

plot_inclusion(
  X = MCS_est_included,
  nstep = nstep,
  lab_full = lab_full,
  r_t_plot = r_t_oos_full_plot,
  N_model = 32,
  square_col="blue",
  input_type = "MCS"
)

###################################
#### Replication of Figure 2(c)
###################################

plot_inclusion(
  X = MCS_est_included_w,
  nstep = nstep,
  lab_full = lab_full,
  r_t_plot = r_t_oos_full_plot,
  N_model = 32,
  square_col="black",
  input_type = "MCS"
)

###################################
#### Code for replication of Table 5 
###################################

# The user can load either "data/results/sp500_final_results_precomputed.RData" or 
# "data/results/sp500_final_results_generated.RData" generated by "code/3_from_intermediary_files_to_final_files.R"

load("data/results/sp500_final_results_precomputed.RData")

#############################################################################
#### sp500_final_results_precomputed includes:
## r_t_oos_full_plot				: daily log-returns for the training plots;
## r_t_oos_full					: daily log-returns for the out-of-sample period;
## nstep							: total number of model re-estimations (i.e., length of the out-of-sample period);
## lab_full						: model labels, including 32 models, 4 benchmarks (EW-Comb, Median-Comb, RS-Comb, MS-Comb),
##           							and 6 proposed combined predictors (MCS-Comb, WL-MCS-Comb, MCS-RS-Comb, WL-MCS-RS-Comb, 
##           							MCS-MS-Comb, WL-MCS-MS-Comb);
## tau							: coverage level;
## Backtesting_pvalues			: p-values of the six backtests (see Table 4 in the paper), by model (32) and over nstep;
## db_loss_oos					: matrix of FZ losses for the out-of-sample period for the 42 models and combined predictors;
## VaR_oos_ev and ES_oos_ev		: matrices of VaR and ES for the out-of-sample period
##                           			for the 42 models and combined predictors;
## MCS_est_included				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                  					from the Model Confidence Set (MCS), using the unweighted FZ loss;
## MCS_est_included_w				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                     				from the Model Confidence Set (MCS), using the weighted FZ loss.
#############################################################################

#### Setting of the MCS

set.seed(123)

B <- 1000                  		# number of bootstrap replicates for the MCS
alpha <- 0.25              		# significance level for the MCS
N_model_full <- length(lab_full)   # total number of models and combined predictors

#### Store the averages

col_means<-colMeans(db_loss_oos)

#### Evaluation MCS

MCS_est_with_c<-MCS_f(db_loss_oos,B=B,alpha=alpha)

col_mcs<-cbind(
round(col_means,3),
ifelse(1:N_model_full %in% MCS_est_with_c$includedR,1,0)
)

colnames(col_mcs)<-c("FZLoss","SSM")

#### VaR backtesting

cols_var<-matrix(rep(NA,3*N_model_full),ncol=3)

for (i in 1:N_model_full){
cols_var[i,1]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau)$LRuc[2])
cols_var[i,2]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau)$LRcc[2])
cols_var[i,3]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau, Lags = 2)$DQ[2])
}

cols_var<-round(cols_var,3)

colnames(cols_var)<-c("UC","CC","DQ")

#### ES backtesting

cols_es<-matrix(rep(NA,3*N_model_full),ncol=3)

r_t_oos<-coredata(r_t_oos_full)

for (i in 1:N_model_full){
# Bayer & Dimitriadis (2020) test version 1
cols_es[i,1]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 1)$pvalue_twosided_asymptotic)
# Bayer & Dimitriadis (2020) test version 2
cols_es[i,2]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 2)$pvalue_twosided_asymptotic)
# Bayer & Dimitriadis (2020) test version 3
cols_es[i,3]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 3)$pvalue_twosided_asymptotic)
message(i)
}

colnames(cols_es)<-c("BD-1","BD-2","BD-3")
cols_es<-round(cols_es,3)

final_tab<-cbind(cols_var,cols_es,col_mcs)
rownames(final_tab)<-lab_full

### 1 if all backtests are passed (p-values >= 0.05), 0 otherwise
Backtest_all <- as.integer(rowSums(final_tab[, 1:6] >= 0.05) == 6)

final_tab<-cbind(final_tab,Backtest=Backtest_all)
final_tab_latex <- add_latex_markers(final_tab)

######################################
#### Replication of Table 5
######################################

# To reproduce exactly the p-values of the Bayer & Dimitriadis (2020) tests reported in the paper, 
# the code should be run under R version 4.4.3.
# When using different R versions or computing environments, small numerical differences may arise;
# these affect only the p-values of these tests and do not alter the main conclusions.

tab_dt_f(final_tab, title = "Table 5: S&P 500 out-of-sample evaluation")

######################################
#### Code for replication of Table 6 
######################################

## To ensure full reproducibility of the esr_backtest results, 
## each index should be evaluated in a separate fresh R session after setting the random seed.


# The user can load either "data/results/shanghai_comp_final_results_precomputed.RData" or 
# "data/results/shanghai_comp_final_results_generated.RData" generated by "code/3_from_intermediary_files_to_final_files.R"

load("data/results/shanghai_comp_final_results_precomputed.RData")

#############################################################################
#### shanghai_comp_final_results_precomputed includes:
## r_t_oos_full_plot				: daily log-returns for the training plots;
## r_t_oos_full					: daily log-returns for the out-of-sample period;
## nstep							: total number of model re-estimations (i.e., length of the out-of-sample period);
## lab_full						: model labels, including 32 models, 4 benchmarks (EW-Comb, Median-Comb, RS-Comb, MS-Comb),
##           							and 6 proposed combined predictors (MCS-Comb, WL-MCS-Comb, MCS-RS-Comb, WL-MCS-RS-Comb, 
##           							MCS-MS-Comb, WL-MCS-MS-Comb);
## tau							: coverage level;
## Backtesting_in_sample_pvalues	: p-values of the six backtests (see Table 4 in the paper), by model (32) and over nstep;
## db_loss_oos					: matrix of FZ losses for the out-of-sample period for the 42 models and combined predictors;
## VaR_oos_ev and ES_oos_ev		: matrices of VaR and ES for the out-of-sample period
##                           			for the 42 models and combined predictors;
## MCS_est_included				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                  					from the Model Confidence Set (MCS), using the unweighted FZ loss;
## MCS_est_included_w				: list of models included at each step (nstep) in the Set of Superior Models (SSM)
##                     				from the Model Confidence Set (MCS), using the weighted FZ loss.
#############################################################################


#### Setting of the MCS

B <- 1000                  		# number of bootstrap replicates for the MCS
alpha <- 0.25              		# significance level for the MCS
N_model_full <- length(lab_full)   # total number of models and combined predictors

#### Store the averages

col_means<-colMeans(db_loss_oos)

#### Evaluation MCS

MCS_est_with_c<-MCS_f(db_loss_oos,B=B,alpha=alpha)

col_mcs<-cbind(
round(col_means,3),
ifelse(1:N_model_full %in% MCS_est_with_c$includedR,1,0)
)

colnames(col_mcs)<-c("FZLoss","SSM")

#### VaR backtesting

cols_var<-matrix(rep(NA,3*N_model_full),ncol=3)

for (i in 1:N_model_full){
cols_var[i,1]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau)$LRuc[2])
cols_var[i,2]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau)$LRcc[2])
cols_var[i,3]<-as.numeric(BacktestVaR(r_t_oos_full, VaR_oos_ev[,i], tau, Lags = 2)$DQ[2])
}

cols_var<-round(cols_var,3)

colnames(cols_var)<-c("UC","CC","DQ")

#### ES backtesting

cols_es<-matrix(rep(NA,3*N_model_full),ncol=3)

r_t_oos<-coredata(r_t_oos_full)

for (i in 1:N_model_full){
# Bayer & Dimitriadis (2020) test version 1
cols_es[i,1]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 1)$pvalue_twosided_asymptotic)
# Bayer & Dimitriadis (2020) test version 2
cols_es[i,2]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 2)$pvalue_twosided_asymptotic)
# Bayer & Dimitriadis (2020) test version 3
cols_es[i,3]<-as.numeric(esr_backtest(r_t_oos, VaR_oos_ev[,i], ES_oos_ev[,i],tau, version = 3)$pvalue_twosided_asymptotic)
message(i)
}

colnames(cols_es)<-c("BD-1","BD-2","BD-3")
cols_es<-round(cols_es,3)

final_tab<-cbind(cols_var,cols_es,col_mcs)
rownames(final_tab)<-lab_full

### 1 if all backtests are passed (p-values >= 0.05), 0 otherwise
Backtest_all <- as.integer(rowSums(final_tab[, 1:6] >= 0.05) == 6)

final_tab<-cbind(final_tab,Backtest=Backtest_all)

###################################
#### Replication of Table 6
###################################

# As for Table 5, to reproduce exactly the p-values of the Bayer & Dimitriadis (2020) tests reported in the paper, 
# the code should be run under R version 4.4.3.
# When using different R versions or computing environments, small numerical differences may arise;
# these affect only the p-values of these tests and do not alter the main conclusions.

tab_dt_f(final_tab, title = "Table 6: Shanghai Composite out-of-sample evaluation")

###################################
#### Replication of Table 7
###################################

######################################################################
# Table 7 can be directly replicated using the pre-computed files:
#   - all_indices_tau_0.025.RData
#   - all_indices_tau_0.01.RData
#
# These files contain the evaluation tables for all nine indices
# considered in the paper. Each evaluation table corresponds to the
# type of output reported in Tables 5 and 6, i.e., the detailed
# backtesting and FZLoss results for a single index. The evaluation
# tables stored in these files already include the LaTeX markers used
# in the published version of the paper:
#
#   - cellcolor{gray!25}: models passing all six backtests;
#   - cellcolor{gray!50}: models belonging to the Superior Set of
#                           Models (SSM) of the Model Confidence Set.
#
# Table 7 is obtained by aggregating the information contained in
# these evaluation tables across all nine indices and both coverage
# levels.
#
# Alternatively, users can fully regenerate the evaluation tables
# from the raw data. For each index and coverage level, this can be
# done by running Scripts 2, 3, and Script 4 (lines 13--31 and 133--194).
#
# The object final_tab_latex obtained at line 194 corresponds to the
# evaluation table for a single index and should be stored as an
# element of the list "list_of_tabs". After repeating this procedure
# for all nine indices, "list_of_tabs" will contain the nine evaluation
# tables required to reproduce Table 7. This has to be repeated for 
# all the coverage levels.
######################################################################

load("data/results/all_indices_tau_0.025.RData")

#######################################################################################
#### all_indices_tau_0.025 includes:
## list_of_tabs	: list of tables (one per index) with models in rows and
##               		backtesting p-values (UC, CC, DQ, BD-1, BD-2, BD-3) and FZLoss in columns;
##               		LaTeX markers (e.g., cellcolor{...}) indicate whether models pass all backtests at the 5% level
##               		and belong to the SSM of the MCS at the 25% significance level; 
## lab_full		: model labels, including 32 models, 4 benchmarks (EW-Comb, Median-Comb, RS-Comb, MS-Comb),
##           			and 6 proposed combined predictors (MCS-Comb, WL-MCS-Comb, MCS-RS-Comb, WL-MCS-RS-Comb, 
##          			MCS-MS-Comb, WL-MCS-MS-Comb).
## VaR and ES are estimated at the 2.5% level.
#######################################################################################

res_final_0.025 <- build_summary_from_list(
  tabs_list = list_of_tabs,
  lab_full = lab_full,
  as_percent = FALSE
)

rm(list_of_tabs)

load("data/results/all_indices_tau_0.01.RData")

#######################################################################################
#### all_indices_tau_0.01 includes:
## list_of_tabs	: list of tables (one per index) with models in rows and
##               		backtesting p-values (UC, CC, DQ, BD-1, BD-2, BD-3) and FZLoss in columns;
##               		LaTeX markers (e.g., cellcolor{...}) indicate whether models pass all backtests at the 5% level
##               		and belong to the SSM of the MCS at the 25% significance level; 
## lab_full		: model labels, including 32 models, 4 benchmarks (EW-Comb, Median-Comb, RS-Comb, MS-Comb),
##           			and 6 proposed combined predictors (MCS-Comb, WL-MCS-Comb, MCS-RS-Comb, WL-MCS-RS-Comb, 
##          			MCS-MS-Comb, WL-MCS-MS-Comb).
## VaR and ES are estimated at the 1% level.
#######################################################################################

res_final_0.01 <- build_summary_from_list(
  tabs_list = list_of_tabs,
  lab_full = lab_full,
  as_percent = FALSE
)

tab_7<-cbind(res_final_0.025,res_final_0.01)
tab_7

### Table 7 in hmtl
tab_7_dt_f(tab_7,
title= "Table 7: Summary of successful backtests and MCS inclusions across indices and coverage
levels")


